- hosts: all
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

- hosts: nginx
  become: true
  vars:
    server_name: "{{ inventory_hostname }}"
    html_root: /var/www/html
    file_name: index.html
  tasks:
    - name: Update apt cache and install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Apply Index.html template
      template:
        src: index.html.j2
        dest: "{{ html_root }}/{{ file_name }}"
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
